server.port: 8080

spring.profiles.active:
  - development
  - msa-api

ocr4all:
  message.topic:
    prefix: /topic
    end-point: /spi-event
  thread.pool.size: 
    standard: 6
    time-consuming: 3
  projects.folder: /home/ocr4all/projects
  ocrd:
    parameter.description.json: -J
    processors.time-consuming: ocrd-calamari-recognize,ocrd-tesserocr-recognize

---
spring:
    config.activate.on-profile: docker

logging:
  file:
    path: /var/log/ocr4all
    name: ocr4all.log
  level:
    root: INFO

---
spring:
    config.activate.on-profile: development

server:
  port: 9091
  error.include-stacktrace: always

logging:
  file:
    path:
    name:
  level:
    "[de.uniwuerzburg.zpd.ocr4all.application.ocrd.msa]": DEBUG

